version: "2"
services:
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    networks:
      - backend
    ports:
      - "8002:8025"

  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    networks:
      - backend
    hostname: "rabbitmq"
    ports:
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - backend

  mariadb:
    image: mariadb
    container_name: mariadb
    networks:
      - backend
    command: mysqld --innodb-buffer-pool-size=20M
    volumes:
      - "./mariadb/data:/var/lib/mysql:rw"
    environment:
      - "MYSQL_DATABASE=app"
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=123"
      - "MYSQL_ROOT_PASSWORD=123"
    ports:
      - "3306:3306"

  app:
    build:
      context: ../
      dockerfile: ./env/app/Dockerfile
    container_name: app
    networks:
      - backend
    environment:
      XDEBUG_CONFIG: "remote_host=10.0.75.1"
      PHP_IDE_CONFIG: "serverName=backend.dev"
    volumes:
      - ../src/:/var/www/html
      - ./app/sites/default.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "80:80"

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.200.0.0/16
          gateway: 172.200.0.1