version: "2.3"
services:
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    networks:
      - backend
    ports:
      - "8002:8025"

  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    networks:
      - backend
    hostname: "evotor-rabbitmq"
    ports:
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - backend

  mariadb:
    image: mariadb
    container_name: mariadb
    networks:
      - backend
    command: mysqld --innodb-buffer-pool-size=20M
    volumes:
      - "./mariadb/data:/var/lib/mysql:rw"
    environment:
      - "MYSQL_DATABASE=app"
      - "MYSQL_USER=app"
      - "MYSQL_PASSWORD=oLd12niV8k"
      - "MYSQL_ROOT_PASSWORD=IivahW03oc"
    ports:
      - "3306:3306"

  httpserver:
    image: nginx:latest
    build:
      context: nginx
    container_name: httpserver
    networks:
      - backend
    ports:
     - "80:80"

  app:
    build:
      context: ../
      dockerfile: ./env/app/Dockerfile
      target: dev
    container_name: app
    networks:
      - backend
    volumes:
      - ../src/:/var/www/html

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.200.0.0/16